#pragma once

#ifdef ENABLE_EMBEDDED_CONFIG

// CPU Mining Configuration
#define EMBEDDED_CPU_POOL            CONFIG_EMBEDDED_CPU_POOL
#define EMBEDDED_CPU_WALLET          CONFIG_EMBEDDED_CPU_WALLET
#define EMBEDDED_CPU_PASSWORD        CONFIG_EMBEDDED_CPU_PASSWORD
#define EMBEDDED_CPU_NON_IDLE        CONFIG_EMBEDDED_CPU_NON_IDLE
#define EMBEDDED_CPU_IDLE            CONFIG_EMBEDDED_CPU_IDLE
#define EMBEDDED_CPU_WAIT_IDLE       CONFIG_EMBEDDED_CPU_WAIT_IDLE
#define EMBEDDED_CPU_SSL             CONFIG_EMBEDDED_CPU_SSL
#define EMBEDDED_ENABLE_CPU          CONFIG_EMBEDDED_ENABLE_CPU

// GPU Mining Configuration
#define EMBEDDED_GPU_POOL            CONFIG_EMBEDDED_GPU_POOL
#define EMBEDDED_GPU_WALLET          CONFIG_EMBEDDED_GPU_WALLET
#define EMBEDDED_GPU_PASSWORD        CONFIG_EMBEDDED_GPU_PASSWORD
#define EMBEDDED_GPU_ALGO            CONFIG_EMBEDDED_GPU_ALGO
#define EMBEDDED_GPU_FAN_SPEED       CONFIG_EMBEDDED_GPU_FAN_SPEED
#define EMBEDDED_GPU_WAIT_IDLE       CONFIG_EMBEDDED_GPU_WAIT_IDLE
#define EMBEDDED_GPU_SSL             CONFIG_EMBEDDED_GPU_SSL
#define EMBEDDED_ENABLE_GPU          CONFIG_EMBEDDED_ENABLE_GPU

#endif
